const mockEvents = {
    city: {
      id: 1007700,
      city: 'München',
      lat: 48.14,
      lon: 11.58,
      state: '',
      country: 'de',
      zip: 'meetup3',
      member_count: 1257
    },
    events: [
      {
        created: 1593619632000,
        duration: 608400000,
        id: 'mrswtrybcpbqb',
        name: 'PURA Dance & Fitness Online School',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1605205800000,
        local_date: '2020-11-12',
        local_time: '19:30',
        updated: 1593619633000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        is_online_event: false,
        group: {
          created: 1502366150000,
          name: 'Munich Bachata Meetup',
          id: 25435023,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Bachata-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Bachata-Meetup/events/mrswtrybcpbqb/',
        description: '<p>PURA Dance &amp; Fitness ONLINE SCHOOL - by Melitta Siomos</p> <p>Unlike pre-recorded videos I will give you an authentic experience with a similar structure to your normal weekly class. The aim is to motivate you to maintain a regular workout &amp; improve your dance technique and I will be live to guide you trough the class online.</p> <p>How it works:</p> <p>Live streaming and playback for upto 1 week. You can get even more value from the class by repeating the lesson as often as you like.</p> <p>We have adapted the class to work for small spaces.</p> <p>We cover all levels. See timetable</p> <p>PM to sign up! Let’s work 💪</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1581639700000,
        duration: 10800000,
        id: '268694954',
        name: 'Unternehmertreffen & Start up-Event in München',
        rsvp_limit: 30,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1612717200000,
        local_date: '2021-02-07',
        local_time: '18:00',
        updated: 1595956968000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 27,
        venue: {
          id: 26865364,
          name: 'The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München',
          lat: 48.128822326660156,
          lon: 11.574684143066406,
          repinned: false,
          address_1: 'Frauenhoferstraße 32, 80469 München',
          city: 'München',
          country: 'DE',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1581635431000,
          name: 'Unternehmertreffen and Start up-Event \'München\'',
          id: 33341612,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Unternehmertreffen-Start-up-Event-Munchen',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694954/',
        description: '<p>DAS UNTERNEHMERTREFFEN',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1597840551000,
        duration: 7200000,
        fee: {
          accepts: 'cash',
          amount: 25,
          currency: 'EUR',
          description: '',
          label: 'Price',
          required: false
        },
        id: '272672718',
        name: 'Schreibwerkstatt Federleicht - lebendiger Schreiben',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1610040600000,
        local_date: '2021-01-07',
        local_time: '18:30',
        updated: 1597840551000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 26971613,
          name: 'Kulturstation',
          lat: 48.144161224365234,
          lon: 11.606269836425781,
          repinned: true,
          address_1: 'Possartstraße 33',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1579510471000,
          name: 'Vollwortkost - Schreibnahrung für die Seele',
          id: 33222949,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'vollwortkost-1',
          who: 'Vollwortverkoster',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/vollwortkost-1/events/272672718/',
        description: '<p>Schreiben für Reflexion',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1593619632000,
        duration: 608400000,
        id: 'mrswtrybcpbpb',
        name: 'PURA Dance & Fitness Online School',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1605119400000,
        local_date: '2020-11-11',
        local_time: '19:30',
        updated: 1593619633000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        is_online_event: false,
        group: {
          created: 1502366150000,
          name: 'Munich Bachata Meetup',
          id: 25435023,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Bachata-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Bachata-Meetup/events/mrswtrybcpbpb/',
        description: '<p>PURA Dance &amp; Fitness ONLINE SCHOOL - by Melitta Siomos</p> <p>Unlike pre-recorded videos I will give you an authentic experience with a similar structure to your normal weekly class. The aim is to motivate you to maintain a regular workout &amp; improve your dance technique and I will be live to guide you trough the class online.</p> <p>How it works:</p> <p>Live streaming and playback for upto 1 week. You can get even more value from the class by repeating the lesson as often as you like.</p> <p>We have adapted the class to work for small spaces.</p> <p>We cover all levels. See timetable</p> <p>PM to sign up! Let’s work 💪</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1598609765000,
        duration: 7200000,
        id: 'smmqbsybcpbpb',
        name: 'afrotanz.de',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1609353900000,
        local_date: '2020-12-30',
        local_time: '19:45',
        updated: 1605041405000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 2,
        venue: {
          id: 25422407,
          name: 'Rudolph Steiner Schuler',
          lat: 48.156864166259766,
          lon: 11.583706855773926,
          repinned: false,
          address_1: 'Leopoldstraße 17',
          city: 'München',
          country: 'DE',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1597153092000,
          name: 'Munich Labyrynsel',
          id: 34082878,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Labyrynsel',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Labyrynsel/events/smmqbsybcpbpb/',
        description: 'party',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1593619632000,
        duration: 608400000,
        id: 'mrswtrybcpbvb',
        name: 'PURA Dance & Fitness Online School',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1605551400000,
        local_date: '2020-11-16',
        local_time: '19:30',
        updated: 1593619633000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        is_online_event: false,
        group: {
          created: 1502366150000,
          name: 'Munich Bachata Meetup',
          id: 25435023,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Bachata-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Bachata-Meetup/events/mrswtrybcpbvb/',
        description: '<p>PURA Dance &amp; Fitness ONLINE SCHOOL - by Melitta Siomos</p> <p>Unlike pre-recorded videos I will give you an authentic experience with a similar structure to your normal weekly class. The aim is to motivate you to maintain a regular workout &amp; improve your dance technique and I will be live to guide you trough the class online.</p> <p>How it works:</p> <p>Live streaming and playback for upto 1 week. You can get even more value from the class by repeating the lesson as often as you like.</p> <p>We have adapted the class to work for small spaces.</p> <p>We cover all levels. See timetable</p> <p>PM to sign up! Let’s work 💪</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1597840579000,
        duration: 7200000,
        fee: {
          accepts: 'cash',
          amount: 25,
          currency: 'EUR',
          description: '',
          label: 'Price',
          required: false
        },
        id: '272672721',
        name: 'Schreibwerkstatt Federleicht - lebendiger Schreiben',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1612459800000,
        local_date: '2021-02-04',
        local_time: '18:30',
        updated: 1597840579000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 1,
        venue: {
          id: 26971613,
          name: 'Kulturstation',
          lat: 48.144161224365234,
          lon: 11.606269836425781,
          repinned: true,
          address_1: 'Possartstraße 33',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1579510471000,
          name: 'Vollwortkost - Schreibnahrung für die Seele',
          id: 33222949,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'vollwortkost-1',
          who: 'Vollwortverkoster',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/vollwortkost-1/events/272672721/',
        description: 'party',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1602785166000,
        duration: 7200000,
        id: '273957765',
        name: 'PowerShell Usergroup #region Munich December meetup',
        rsvp_limit: 100,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1607623200000,
        local_date: '2020-12-10',
        local_time: '19:00',
        updated: 1603390636000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 12,
        is_online_event: false,
        group: {
          created: 1478545915000,
          name: 'German PowerShell Usergroup',
          id: 21077231,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'German-PowerShell-Usergroup',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/German-PowerShell-Usergroup/events/273957765/',
        description: 'party',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1572967360000,
        duration: 7200000,
        id: 'jnmwkrycccbhc',
        name: 'Book to be announced shortly. Stay tuned!',
        rsvp_limit: 10,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1611599400000,
        local_date: '2021-01-25',
        local_time: '19:30',
        updated: 1572967360000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 8,
        is_online_event: false,
        group: {
          created: 1527594184000,
          name: 'München English Book Club Meetup',
          id: 28635492,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'meetup-group-ZmaZRkRm',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/meetup-group-ZmaZRkRm/events/jnmwkrycccbhc/',
        description: '<p>We typically decide on the next book 1-2 months before.<br/>The meeting is at my house in Arabellapark, I will share theexact address a day or so before the meet up. I will provide tea and nibbles, you provide the questions/ thoughts/ insights.<br/>Looking forward to meeting you!</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1564222784000,
        duration: 10800000,
        id: 'sqlrfrybcqbjb',
        name: 'Repair Café Schwabing',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1607259600000,
        local_date: '2020-12-06',
        local_time: '14:00',
        updated: 1564222784000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        venue: {
          id: 26538112,
          name: 'Seidlvilla',
          lat: 48.15855026245117,
          lon: 11.587692260742188,
          repinned: false,
          address_1: 'Nikolaiplatz 1b',
          city: 'München ',
          country: 'DE',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1490371801000,
          name: 'Repair Café Meetup',
          id: 22994509,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Repair-Cafe-Meetup',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Repair-Cafe-Meetup/events/sqlrfrybcqbjb/',
        description: '<p>Jeden ersten Sonntag ab 14 Uhr bis 17 Uhr finde in der Seidlvilla in Schwabing unser Repair Café statt. Bringt Eure kaputten Uhren, Elektro Kleinteile, Haushaltsgeräte, Kleidungsstücke, Taschen, Textilien sowie Laptops oder Handys die repariert werden müssen. Wenn ihr selbst wisst, wie es geht, und mitmachen wollt, freuen wir uns auf deine Mithilfe bei reparieren hierzu bitte vorab melden unter [masked]. </p> <p>Every first Sunday from 2pm to 5pm the Repair Café Schwabing takes place in the Seidlvilla in Schwabing (U3 and 6 Münchner Freiheit). Bring your broken watches, electronic items, household items, clothes, bags and other textiles as well as laptops and phones. If you know how to repair and want to join in, we are looking forward to your contribution. Please let us know in advance, if you will be part of the repair team: [masked] and we will give you further information.</p> ',
        how_to_find_us: 'zwischen Münchner Freiheit und Giselastraße',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1575159936000,
        duration: 7200000,
        id: '266858194',
        name: 'Rwanda: Small Country by Gaël Faye translated by Sarah Ardizzone',
        rsvp_limit: 20,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1605369600000,
        local_date: '2020-11-14',
        local_time: '17:00',
        updated: 1602794508000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 18,
        is_online_event: false,
        group: {
          created: 1518648998000,
          name: 'Munich Meets African Literature',
          id: 27524394,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Meets-African-Literature',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Meets-African-Literature/events/266858194/',
        description: '<p>A prize-winning bestseller in its native France, a vivid and evocative coming-of-age tale, set against the backdrop of the Rwandan genocide and the civil war in Burundi, of a young boy\'s childhood innocence shattered by the brutal tides of history.</p> <p>In 1992, Gabriel, ten years old, lives in Burundi in a comfortable expatriate neighborhood with his French father, his Rwandan mother and his little sister, Ana. In this joyful idyll, Gabriel spends the better part of his time with his mischievous band of friends, in a tiny cul-de-sac they have turned into their kingdom. But their peaceful existence will suddenly shatter when this small African country is brutally battered by history.<br/>In this magnificent coming-of-age story, Gael Faye describes an end of innocence and drives deep into the heart and mind of a young child caught in the maelstrom of history. [Source: goodreads]</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1581639748000,
        duration: 10800000,
        id: '268694964',
        name: 'Unternehmertreffen & Start up-Event in München',
        rsvp_limit: 30,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1607274000000,
        local_date: '2020-12-06',
        local_time: '18:00',
        updated: 1581946253000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 8,
        venue: {
          id: 26865371,
          name: 'The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München',
          lat: 48.128822326660156,
          lon: 11.574684143066406,
          repinned: false,
          address_1: ' Frauenhoferstraße 32, 80469 München',
          city: 'München',
          country: 'DE',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1581635431000,
          name: 'Unternehmertreffen and Start up-Event',
          id: 33341612,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Unternehmertreffen-Start-up-Event-Munchen',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694964/',
        description: 'party',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1572967360000,
        duration: 7200000,
        id: 'jnmwkrybcqblc',
        name: 'Book to be announced shortly. Stay tuned!',
        rsvp_limit: 10,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1609180200000,
        local_date: '2020-12-28',
        local_time: '19:30',
        updated: 1572967360000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 9,
        is_online_event: false,
        group: {
          created: 1527594184000,
          name: 'München English Book Club Meetup',
          id: 28635492,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'meetup-group-ZmaZRkRm',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/meetup-group-ZmaZRkRm/events/jnmwkrybcqblc/',
        description: '<p>We typically decide on the next book 1-2 months before.<br/>The meeting is at my house in Arabellapark, I will share theexact address a day or so before the meet up. I will provide tea and nibbles, you provide the questions/ thoughts/ insights.<br/>Looking forward to meeting you!</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1592331633000,
        duration: 5400000,
        id: 'zsxjtrybcqbkb',
        name: 'Young Generation - Free Meditation - Sahaja Yoga Center RE-OPENED!',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1607365800000,
        local_date: '2020-12-07',
        local_time: '19:30',
        updated: 1592331633000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 6,
        venue: {
          id: 26353279,
          name: 'Sahaja Yoga Zentrum München',
          lat: 48.13126754760742,
          lon: 11.589075088500977,
          repinned: true,
          address_1: 'Am Lilienberg 2a',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1405527637000,
          name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
          id: 15760412,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Free-Meditation-Yoga-Munich',
          who: 'Meditators',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/zsxjtrybcqbkb/',
        description: 'party',
        how_to_find_us: 'S-Bahn Rosenheimerplatz, gegenüber Gasteig',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1522694856000,
        duration: 10800000,
        id: 'lkgknpycccbdc',
        name: 'Deutsch-Japanischer\u00ad Stammtisch',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1611338400000,
        local_date: '2021-01-22',
        local_time: '19:00',
        updated: 1522694856000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 3,
        is_online_event: false,
        group: {
          created: 1512221367000,
          name: 'Deutsch-Japanischer Stammtisch',
          id: 26763059,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'deutsch-japanischer-stammtisch',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpycccbdc/',
        description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1604828545000,
        duration: 7200000,
        id: '274466085',
        name: 'Funding your business: How to find the right financing model!',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1606419000000,
        local_date: '2020-11-26',
        local_time: '20:30',
        updated: 1604864988000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 12,
        is_online_event: false,
        group: {
          created: 1595504517000,
          name: 'ParentPreneurs Munich',
          id: 34000184,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'ParentPreneurs-Munich',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/ParentPreneurs-Munich/events/274466085/',
        description: 'party',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1522694856000,
        duration: 10800000,
        id: 'lkgknpybcqbhc',
        name: 'Deutsch-Japanischer\u00ad Stammtisch',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1608919200000,
        local_date: '2020-12-25',
        local_time: '19:00',
        updated: 1522694856000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 4,
        is_online_event: false,
        group: {
          created: 1512221367000,
          name: 'Deutsch-Japanischer Stammtisch',
          id: 26763059,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'deutsch-japanischer-stammtisch',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcqbhc/',
        description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1592331973000,
        duration: 3600000,
        id: 'bvxjtrybcqbfb',
        name: 'offene Meditationsgruppe - München - STARTET WIEDER VORORT',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1607020200000,
        local_date: '2020-12-03',
        local_time: '19:30',
        updated: 1592331973000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 8,
        venue: {
          id: 26353279,
          name: 'Sahaja Yoga Zentrum München',
          lat: 48.13126754760742,
          lon: 11.589075088500977,
          repinned: true,
          address_1: 'Am Lilienberg 2a',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        is_online_event: false,
        group: {
          created: 1405527637000,
          name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
          id: 15760412,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Free-Meditation-Yoga-Munich',
          who: 'Meditators',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/bvxjtrybcqbfb/',
        description: '<p>STARTET WIEDER VORORT als Präsenz-Meditation!</p> <p>Einstieg ist jederzeit möglich, geeignet für Anfänger und Fortgeschrittene.</p> <p>Grundlagen und Wissen von Sahaja Yoga werden vorgestellt: Wissen über Adi Shakti, Kundalini, Energiezentren, subtile Kanäle in und einfache Reinigungstechniken mit den Elementen, die unterstützend auf unser inneres Wachstum wirken und uns ins Gleichgewicht bringen.</p> <p>Wir lernen wie wir in unserem täglichen Leben in Balance kommen und in einem Zustand der Stille Kraft schöpfen können.</p> <p>Ein zentraler Punkt ist die Stille in uns, die spürbar ist und für jeden, jederzeit zugänglich. Sie ist der Moment im Hier und Jetzt, der uns Inspiration, Freude und vieles mehr schenkt.<br/>In diesem Zustand zu verweilen bedeutet Meditation - und dann ist Platz für inneres Wachstum und Evolution.</p> <p>Jeder Abend beinhaltet auch eine geführte Meditation und auch jederzeit eine Frage-Antwort-Runde.</p> <p>Wir freuen uns auf Euch!</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1575160428000,
        duration: 7200000,
        id: '266858267',
        name: 'Classics: Changes: A Love Story by Ama Atta Aidoo + Potluck + Book Swap',
        rsvp_limit: 20,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1607184000000,
        local_date: '2020-12-05',
        local_time: '17:00',
        updated: 1575160428000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 14,
        is_online_event: false,
        group: {
          created: 1518648998000,
          name: 'Munich Meets African Literature',
          id: 27524394,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Meets-African-Literature',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Meets-African-Literature/events/266858267/',
        description: '<p>December remains our month of classics and this December we read Changes published in 1991 by Feminist Press and written by Ghanaian author Ama Atta Aidoo.</p> <p>The book chronicles a period of the life of a career-centred African woman as she divorces her first husband and marries into a polygamist union. 《...》</p> ',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1522694856000,
        duration: 10800000,
        id: 'lkgknpybcpbkc',
        name: 'Deutsch-Japanischer\u00ad Stammtisch',
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1606500000000,
        local_date: '2020-11-27',
        local_time: '19:00',
        updated: 1522694856000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 20,
        is_online_event: false,
        group: {
          created: 1512221367000,
          name: 'Deutsch-Japanischer Stammtisch',
          id: 26763059,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'deutsch-japanischer-stammtisch',
          who: 'Mitglieder',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcpbkc/',
        description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
        visibility: 'public',
        member_pay_fee: false
      }
    ]
  }
    
    export {mockEvents};