const mockEvents = { 
    city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257
    },
    events: [
    {
    created: 1593619632000,
    duration: 608400000,
    id: "mrswtrybcpbgb",
    name: "PURA Dance & Fitness Online School",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1604514600000,
    local_date: "2020-11-04",
    local_time: "19:30",
    updated: 1593619633000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 3,
    is_online_event: false,
    group: {
    created: 1502366150000,
    name: "Munich Bachata Meetup",
    id: 25435023,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munich-Bachata-Meetup",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Munich-Bachata-Meetup/events/mrswtrybcpbgb/",
    description: "<p>PURA Dance &amp; Fitness ONLINE SCHOOL - by Melitta Siomos</p> <p>Unlike pre-recorded videos I will give you an authentic experience with a similar structure to your normal weekly class. The aim is to motivate you to maintain a regular workout &amp; improve your dance technique and I will be live to guide you trough the class online.</p> <p>How it works:</p> <p>Live streaming and playback for upto 1 week. You can get even more value from the class by repeating the lesson as often as you like.</p> <p>We have adapted the class to work for small spaces.</p> <p>We cover all levels. See timetable</p> <p>PM to sign up! Let’s work 💪</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1598609765000,
    duration: 7200000,
    id: "vnpxwrybcpbgb",
    name: "afrotanz.de",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1604515500000,
    local_date: "2020-11-04",
    local_time: "19:45",
    updated: 1598609765000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 1,
    venue: {
    id: 25422407,
    name: "Rudolph Steiner Schuler",
    lat: 48.156864166259766,
    lon: 11.583706855773926,
    repinned: false,
    address_1: "Leopoldstraße 17",
    city: "München",
    country: "DE",
    localized_country_name: "Germany"
    },
    is_online_event: false,
    group: {
    created: 1597153092000,
    name: "Munich Labyrynsel",
    id: 34082878,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munich-Labyrynsel",
    who: "Mitglieder",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Munich-Labyrynsel/events/vnpxwrybcpbgb/",
    description: "<p><a href=\"http://www.afrotanz.de/\" class=\"linkified\">http://www.afrotanz.de/</a><br/><a href=\"http://cheikh-bangoura.com/taenzer.html\" class=\"linkified\">http://cheikh-bangoura.com/taenzer.html</a></p> <p>Einzelstunde: 15.- Euro (Streifenkarte 8x - 110 €)</p> <p>Ort: Turnhalle der Rudolf-Steiner-Schule Schwabing (Untergeschoss)</p> <p>Leopoldstrasse 17</p> <p>80806 München</p> <p>U-Bahn: U3 und U6 Haltestelle Giselastrasse</p> <p>Wenn Interesse besteht, immer alle aktuelle Informationen zu erhalten, schreibt uns einfach eine Email. Wir nehmen Euch in unseren Verteiler auf. Link</p> <p>Zusätzlicher offener Kurs (Kristina Prepoutsidis und Cheikh Bangoura):</p> <p>Sonntags:</p> <p>Kristina (Mittelstufe): 18.00 - 19.30 Uhr (15.- €)</p> <p>Cheikh (Fortgeschrittene) : 19.30 - 21.00 (15.- €)</p> <p>Altkatholische Kirche St. Willibrod am Sendlinger Tor in München</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    local_time: "10:00",
    local_date: "2020-12-08",
    link: "https://www.meetup.com/MomWorks/events/272058142/",
    visibility: "public_limited",
    group: {
    created: 1545316803000,
    name: "MomWorks - Business and Professionals",
    id: 30741693,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "MomWorks",
    who: "PowerMoms",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    waitlist_count: 0,
    yes_rsvp_count: 3,
    duration: 7200000,
    time: 1607418000000,
    utc_offset: 3600000,
    name: "MomWorks Online: Der perfekte Elevator Pitch für 2021",
    id: "272058142"
    },
    {
    created: 1579198420000,
    duration: 10800000,
    id: "267967249",
    name: "#geomobMUC I 2021, Smart Cities & Mobility",
    rsvp_limit: 150,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1611250200000,
    local_date: "2021-01-21",
    local_time: "18:30",
    updated: 1582628614000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 15,
    is_online_event: false,
    group: {
    created: 1551172295000,
    name: "Geomob Munich #geomobMUC",
    id: 31257448,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Geomob-Munich-geomobMUC",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Geomob-Munich-geomobMUC/events/267967249/",
    description: "<p>Welcome to the 1st Geomob meetup of the year 2021. The venue for the meetup is still to be decided.</p> <p>The goal of #geomobMUC will be the same as #geomob London, Barcelona and Lisbon: to provide a forum, to learn and exchange ideas about interesting services and projects that deal with location. Everyone working in or curious about the location space or with location services is welcome! You do not need to be some sort of GIS expert (though GIS experts are of course welcome as well). What we are most interested in is not pure geo technology, but rather the application of new geo technologies in services and products of all kind. The goal is not pitch-presentations or marketing, but rather interesting talks by doers about their experiences.</p> <p>The talks are a chance to learn, but equally important is the dialogue between the attendees.</p> <p>Come by and join us!</p> <p>####################################################################<br/>AGENDA: TBD<br/>####################################################################</p> <p>####################################################################<br/>Spread the word and stay updated<br/>####################################################################</p> <p>Please tell everyone you know who may find the evening interesting. Subscribe on our website to stay updated about all events <a href=\"https://thegeomob.com/\" class=\"linkified\">https://thegeomob.com/</a></p> <p>Our low-volume mailing list serves as a way to remind you of upcoming #geomobs and share brief post-event summaries. <a href=\"https://thegeomob.com/mailing-list\" class=\"linkified\">https://thegeomob.com/mailing-list</a></p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1597840551000,
    duration: 7200000,
    fee: {
    accepts: "cash",
    amount: 25,
    currency: "EUR",
    description: "",
    label: "Price",
    required: false
    },
    id: "272672718",
    name: "Schreibwerkstatt Federleicht - lebendiger Schreiben",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1610040600000,
    local_date: "2021-01-07",
    local_time: "18:30",
   updated: 1597840551000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 1,
    venue: {
    id: 26971613,
    name: "Kulturstation",
    lat: 48.144161224365234,
    lon: 11.606269836425781,
    repinned: true,
    address_1: "Possartstraße 33",
    city: "München",
    country: "de",
    localized_country_name: "Germany"
    },
    is_online_event: false,
    group: {
    created: 1579510471000,
    name: "Vollwortkost - Schreibnahrung für die Seele",
    id: 33222949,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "vollwortkost-1",
    who: "Vollwortverkoster",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/vollwortkost-1/events/272672718/",
    description: "<p>Schreiben für Reflexion, Ruhe und Entspannung</p> <p>Schreiben hat einen positiven Einfluss auf Körper und Geist: Es regt die Fantasie an, reduziert Stress und bringt Selbsterkenntnis. Die Schreibwerkstatt Federleicht nutzt dieses heilsame Potenzial mit kreativen Schreibübungen zum Verweilen im Augenblick. Dabei flitzt die Feder so intuitiv übers Papier, dass sich ein Gefühl der Leichtigkeit einstellt. Die Schreibabende sind offen für alle, die Schreiben als Methode für mehr Achtsamkeit, Selbstreflexion oder Entspannung nutzen möchten. Bitte Stifte und Papier mitbringen.</p> <p>Veranstalter: Kulturstation München<br/>Kosten: 25 Euro<br/>Verbindliche Anmeldung über Eventbrite: <a href=\"https://www.eventbrite.de/o/kulturstation-18189868975\" class=\"linkified\">https://www.eventbrite.de/o/kulturstation-18189868975</a><br/>Zusätzlich ist nach erfolgter Zusage über Meetup aucheine Barzahlung vor Ort möglich (Betrag bitte passend mitbringen).</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1602785166000,
    duration: 7200000,
    id: "273957765",
    name: "PowerShell Usergroup #region Munich December meetup",
    rsvp_limit: 100,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1607623200000,
    local_date: "2020-12-10",
    local_time: "19:00",
   updated: 1603390636000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 11,
    is_online_event: false,
    group: {
    created: 1478545915000,
    name: "German PowerShell Usergroup",
    id: 21077231,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "German-PowerShell-Usergroup",
    who: "Mitglieder",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/German-PowerShell-Usergroup/events/273957765/",
    description: "<p>#region München MeetUp<br/><a href=\"https://github.com/GPSUG/Munich\" class=\"linkified\">https://github.com/GPSUG/Munich</a></p> <p>-- English below</p> <p>Hi Zusammen,</p> <p>wir möchten trotz #WFH (work from home) den Community-Gedanken am Leben erhalten und liefern unser PowerShell Meetup virtuell.</p> <p>Das virtuelle Event soll möglichst interaktiv und dynamisch gestaltet werden, bringt also eure Fragen und Anregungen gerne mit.</p> <p>Den Meeting link findet ihr kurz vor Start hier auf der Seite.</p> <p>Joint uns gern auf Slack um in Kommunikation zu bleiben! <a href=\"https://github.com/GPSUG/Munich#slack\" class=\"linkified\">https://github.com/GPSUG/Munich#slack</a><br/>____________________________________________________________</p> <p>$Start = \"19:00\" (7PM)<br/>____________________________________________________________</p> <p>The Sessions:</p> <p>############</p> <p>19:00 - 20:00 Powershell by Jason Helmick - PowerShell Product Group (@theJasonHelmick)</p> <p>Jason wil provide a topic and afterwards you can ask him questions directly.</p> <p>20:00 - 20:45 Free Slot</p> <p>Anyone who wants, can submit a session.<br/>______________________________________________________</p> <p>Hi,</p> <p>even during WFH (work from home) we want to keep the community spirit alive by hosting the next PowerShell meetup online.</p> <p>This virtual event is supposed to be open and interactive. Feel free to bring your questions and topics into the discussion.</p> <p>The meeting link will be posted shortly before the event on this site.</p> <p>For all updates look into the Meetup event.</p> <p>Please also consider joining us on Slack to stay in contact before and after the meetup <a href=\"https://github.com/GPSUG/Munich#slack\" class=\"linkified\">https://github.com/GPSUG/Munich#slack</a></p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1572967360000,
    duration: 7200000,
    id: "jnmwkrycccbhc",
    name: "Book to be announced shortly. Stay tuned!",
    rsvp_limit: 10,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1611599400000,
    local_date: "2021-01-25",
    local_time: "19:30",
   updated: 1572967360000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 8,
    is_online_event: false,
    group: {
    created: 1527594184000,
    name: "München English Book Club Meetup",
    id: 28635492,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "meetup-group-ZmaZRkRm",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/meetup-group-ZmaZRkRm/events/jnmwkrycccbhc/",
    description: "<p>We typically decide on the next book 1-2 months before.<br/>The meeting is at my house in Arabellapark, I will share theexact address a day or so before the meet up. I will provide tea and nibbles, you provide the questions/ thoughts/ insights.<br/>Looking forward to meeting you!</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1564222784000,
    duration: 10800000,
    id: "sqlrfrybcqbjb",
    name: "Repair Café Schwabing",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1607259600000,
    local_date: "2020-12-06",
    local_time: "14:00",
   updated: 1564222784000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 2,
    venue: {
    id: 26538112,
    name: "Seidlvilla",
    lat: 48.15855026245117,
    lon: 11.587692260742188,
    repinned: false,
    address_1: "Nikolaiplatz 1b",
    city: "München ",
    country: "DE",
    localized_country_name: "Germany"
    },
    is_online_event: false,
    group: {
    created: 1490371801000,
    name: "Repair Café Meetup",
    id: 22994509,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Repair-Cafe-Meetup",
    who: "Mitglieder",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Repair-Cafe-Meetup/events/sqlrfrybcqbjb/",
    description: "<p>Jeden ersten Sonntag ab 14 Uhr bis 17 Uhr finde in der Seidlvilla in Schwabing unser Repair Café statt. Bringt Eure kaputten Uhren, Elektro Kleinteile, Haushaltsgeräte, Kleidungsstücke, Taschen, Textilien sowie Laptops oder Handys die repariert werden müssen. Wenn ihr selbst wisst, wie es geht, und mitmachen wollt, freuen wir uns auf deine Mithilfe bei reparieren hierzu bitte vorab melden unter [masked]. </p> <p>Every first Sunday from 2pm to 5pm the Repair Café Schwabing takes place in the Seidlvilla in Schwabing (U3 and 6 Münchner Freiheit). Bring your broken watches, electronic items, household items, clothes, bags and other textiles as well as laptops and phones. If you know how to repair and want to join in, we are looking forward to your contribution. Please let us know in advance, if you will be part of the repair team: [masked] and we will give you further information.</p> ",
    how_to_find_us: "zwischen Münchner Freiheit und Giselastraße",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1593619632000,
    duration: 608400000,
    id: "mrswtrybcpbmb",
    name: "PURA Dance & Fitness Online School",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1604946600000,
    local_date: "2020-11-09",
    local_time: "19:30",
   updated: 1593619633000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 1,
    is_online_event: false,
    group: {
    created: 1502366150000,
    name: "Munich Bachata Meetup",
    id: 25435023,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munich-Bachata-Meetup",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Munich-Bachata-Meetup/events/mrswtrybcpbmb/",
    description: "<p>PURA Dance &amp; Fitness ONLINE SCHOOL - by Melitta Siomos</p> <p>Unlike pre-recorded videos I will give you an authentic experience with a similar structure to your normal weekly class. The aim is to motivate you to maintain a regular workout &amp; improve your dance technique and I will be live to guide you trough the class online.</p> <p>How it works:</p> <p>Live streaming and playback for upto 1 week. You can get even more value from the class by repeating the lesson as often as you like.</p> <p>We have adapted the class to work for small spaces.</p> <p>We cover all levels. See timetable</p> <p>PM to sign up! Let’s work 💪</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1575159936000,
    duration: 7200000,
    id: "266858194",
    name: "Rwanda: Small Country by Gaël Faye translated by Sarah Ardizzone",
    rsvp_limit: 20,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1605369600000,
    local_date: "2020-11-14",
    local_time: "17:00",
   updated: 1602794508000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 15,
    is_online_event: false,
    group: {
    created: 1518648998000,
    name: "Munich Meets African Literature",
    id: 27524394,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munich-Meets-African-Literature",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Munich-Meets-African-Literature/events/266858194/",
    description: "<p>A prize-winning bestseller in its native France, a vivid and evocative coming-of-age tale, set against the backdrop of the Rwandan genocide and the civil war in Burundi, of a young boy's childhood innocence shattered by the brutal tides of history.</p> <p>In 1992, Gabriel, ten years old, lives in Burundi in a comfortable expatriate neighborhood with his French father, his Rwandan mother and his little sister, Ana. In this joyful idyll, Gabriel spends the better part of his time with his mischievous band of friends, in a tiny cul-de-sac they have turned into their kingdom. But their peaceful existence will suddenly shatter when this small African country is brutally battered by history.<br/>In this magnificent coming-of-age story, Gael Faye describes an end of innocence and drives deep into the heart and mind of a young child caught in the maelstrom of history. [Source: goodreads]</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1593619632000,
    duration: 608400000,
    id: "mrswtrybcpbhb",
    name: "PURA Dance & Fitness Online School",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1604601000000,
    local_date: "2020-11-05",
    local_time: "19:30",
   updated: 1593619633000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 1,
    is_online_event: false,
    group: {
    created: 1502366150000,
    name: "Munich Bachata Meetup",
    id: 25435023,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munich-Bachata-Meetup",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Munich-Bachata-Meetup/events/mrswtrybcpbhb/",
    description: "<p>PURA Dance &amp; Fitness ONLINE SCHOOL - by Melitta Siomos</p> <p>Unlike pre-recorded videos I will give you an authentic experience with a similar structure to your normal weekly class. The aim is to motivate you to maintain a regular workout &amp; improve your dance technique and I will be live to guide you trough the class online.</p> <p>How it works:</p> <p>Live streaming and playback for upto 1 week. You can get even more value from the class by repeating the lesson as often as you like.</p> <p>We have adapted the class to work for small spaces.</p> <p>We cover all levels. See timetable</p> <p>PM to sign up! Let’s work 💪</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1572967360000,
    duration: 7200000,
    id: "jnmwkrybcqblc",
    name: "Book to be announced shortly. Stay tuned!",
    rsvp_limit: 10,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1609180200000,
    local_date: "2020-12-28",
    local_time: "19:30",
   updated: 1572967360000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 9,
    is_online_event: false,
    group: {
    created: 1527594184000,
    name: "München English Book Club Meetup",
    id: 28635492,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "meetup-group-ZmaZRkRm",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/meetup-group-ZmaZRkRm/events/jnmwkrybcqblc/",
    description: "<p>We typically decide on the next book 1-2 months before.<br/>The meeting is at my house in Arabellapark, I will share theexact address a day or so before the meet up. I will provide tea and nibbles, you provide the questions/ thoughts/ insights.<br/>Looking forward to meeting you!</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1592331633000,
    duration: 5400000,
    id: "zsxjtrybcqbkb",
    name: "Young Generation - Free Meditation - Sahaja Yoga Center RE-OPENED!",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1607365800000,
    local_date: "2020-12-07",
    local_time: "19:30",
   updated: 1592331633000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 6,
    venue: {
    id: 26353279,
    name: "Sahaja Yoga Zentrum München",
    lat: 48.13126754760742,
    lon: 11.589075088500977,
    repinned: true,
    address_1: "Am Lilienberg 2a",
    city: "München",
    country: "de",
    localized_country_name: "Germany"
    },
    is_online_event: false,
    group: {
    created: 1405527637000,
    name: "Free Meditation & Yoga – in Munich/München (4.400+ members)",
    id: 15760412,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Free-Meditation-Yoga-Munich",
    who: "Meditators",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Free-Meditation-Yoga-Munich/events/zsxjtrybcqbkb/",
    description: "<p>Sahaja Yoga Center RE-OPENED!</p> <p>Free Meditation class for BEGINNERS &amp; ADVANCED !</p> <p>A Global initiative to change the world by changing ourselves.</p> <p>Info: mobile/whatsapp: [masked] (Ganesh)</p> <p>Video: <a href=\"https://www.youtube.com/watch?v=DrCcHm_M16Y&amp;list=PL11600E36E6E9E4AC\" class=\"embedded\">https://www.youtube.com/watch?v=DrCcHm_M16Y&amp;list=PL11600E36E6E9E4AC</a></p> <p>CoolCheck-Website (<a href=\"http://coolcheck.org/\" class=\"linkified\">http://coolcheck.org/</a>)</p> <p>Life only gets better. You’re about to start an amazing journey.</p> <p>However, it is special because it has the power to completely and totally relax your mind and body while energizing it, leaving you in a state where you are able to do anything and everything.<br/>Now we get down to the technicalities. The first step to achieving a state of meditation is simply desire; you have to want it. For your first meditation, it is best to find a quiet place where you can sit comfortably. Take your shoes, glasses, or any extra items off; basically get ready to relax.<br/>Now you know the body is made of three channels and 7 energy centers. An imbalance in any of these is due to the life we lead. So the first thing we shall do is to cleanse these Centers.</p> ",
    how_to_find_us: "S-Bahn Rosenheimerplatz, gegenüber Gasteig",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1522694856000,
    duration: 10800000,
    id: "lkgknpybcqbhc",
    name: "Deutsch-Japanischer­ Stammtisch",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1608919200000,
    local_date: "2020-12-25",
    local_time: "19:00",
   updated: 1522694856000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 4,
    is_online_event: false,
    group: {
    created: 1512221367000,
    name: "Deutsch-Japanischer Stammtisch",
    id: 26763059,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "deutsch-japanischer-stammtisch",
    who: "Mitglieder",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcqbhc/",
    description: "<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1522694856000,
    duration: 10800000,
    id: "lkgknpycccbdc",
    name: "Deutsch-Japanischer­ Stammtisch",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1611338400000,
    local_date: "2021-01-22",
    local_time: "19:00",
   updated: 1522694856000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 3,
    is_online_event: false,
    group: {
    created: 1512221367000,
    name: "Deutsch-Japanischer Stammtisch",
    id: 26763059,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "deutsch-japanischer-stammtisch",
    who: "Mitglieder",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpycccbdc/",
    description: "<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1592331973000,
    duration: 3600000,
    id: "bvxjtrybcqbfb",
    name: "offene Meditationsgruppe - München - STARTET WIEDER VORORT",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1607020200000,
    local_date: "2020-12-03",
    local_time: "19:30",
   updated: 1592331973000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 8,
    venue: {
    id: 26353279,
    name: "Sahaja Yoga Zentrum München",
    lat: 48.13126754760742,
    lon: 11.589075088500977,
    repinned: true,
    address_1: "Am Lilienberg 2a",
    city: "München",
    country: "de",
    localized_country_name: "Germany"
    },
    is_online_event: false,
    group: {
    created: 1405527637000,
    name: "Free Meditation & Yoga – in Munich/München (4.400+ members)",
    id: 15760412,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Free-Meditation-Yoga-Munich",
    who: "Meditators",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Free-Meditation-Yoga-Munich/events/bvxjtrybcqbfb/",
    description: "<p>STARTET WIEDER VORORT als Präsenz-Meditation!</p> <p>Einstieg ist jederzeit möglich, geeignet für Anfänger und Fortgeschrittene.</p> <p>Grundlagen und Wissen von Sahaja Yoga werden vorgestellt: Wissen über Adi Shakti, Kundalini, Energiezentren, subtile Kanäle in und einfache Reinigungstechniken mit den Elementen, die unterstützend auf unser inneres Wachstum wirken und uns ins Gleichgewicht bringen.</p> <p>Wir lernen wie wir in unserem täglichen Leben in Balance kommen und in einem Zustand der Stille Kraft schöpfen können.</p> <p>Ein zentraler Punkt ist die Stille in uns, die spürbar ist und für jeden, jederzeit zugänglich. Sie ist der Moment im Hier und Jetzt, der uns Inspiration, Freude und vieles mehr schenkt.<br/>In diesem Zustand zu verweilen bedeutet Meditation - und dann ist Platz für inneres Wachstum und Evolution.</p> <p>Jeder Abend beinhaltet auch eine geführte Meditation und auch jederzeit eine Frage-Antwort-Runde.</p> <p>Wir freuen uns auf Euch!</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1552311697000,
    duration: 10800000,
    id: "bvtgtqybcpbqb",
    name: "SynBio Stammtisch München",
    rsvp_limit: 12,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1605207600000,
    local_date: "2020-11-12",
    local_time: "20:00",
   updated: 1552311698000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 7,
    is_online_event: false,
    group: {
    created: 1457712232000,
    name: "SynBio.Munich",
    id: 19694168,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Synthetic-Biology-in-Munich",
    who: "Synthetic Biologists",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Synthetic-Biology-in-Munich/events/bvtgtqybcpbqb/",
    description: "<p>Hello everyone,</p> <p>Each time, we are around 10-20 people from all different backgrounds and share our perspectives and experiences on Biotechnology and Synthetic Biology while enjoying some fantastic dinner. Every time we choose another restaurant and we will update the location in the days before the event.</p> <p>New to the field? Then join us too! For us, Synbio is the place where all disciplines come together to share their excitement about biology. Check out www.synbio.info where we collect everything we discover in this amazing field.</p> <p>Looking forward to get you know soon,</p> <p>Jérôme and everyone else</p> ",
    how_to_find_us: "Aquamarin im Prinzregentenbad, Prinzregentenplatz 8, 81675 München",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1575160428000,
    duration: 7200000,
    id: "266858267",
    name: "Classics: Changes: A Love Story by Ama Atta Aidoo + Potluck + Book Swap",
    rsvp_limit: 20,
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1607184000000,
    local_date: "2020-12-05",
    local_time: "17:00",
   updated: 1575160428000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 14,
    is_online_event: false,
    group: {
    created: 1518648998000,
    name: "Munich Meets African Literature",
    id: 27524394,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munich-Meets-African-Literature",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Munich-Meets-African-Literature/events/266858267/",
    description: "<p>December remains our month of classics and this December we read Changes published in 1991 by Feminist Press and written by Ghanaian author Ama Atta Aidoo.</p> <p>The book chronicles a period of the life of a career-centred African woman as she divorces her first husband and marries into a polygamist union. 《...》</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1522694856000,
    duration: 10800000,
    id: "lkgknpybcpbkc",
    name: "Deutsch-Japanischer­ Stammtisch",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1606500000000,
    local_date: "2020-11-27",
    local_time: "19:00",
   updated: 1522694856000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 18,
    is_online_event: false,
    group: {
    created: 1512221367000,
    name: "Deutsch-Japanischer Stammtisch",
    id: 26763059,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "deutsch-japanischer-stammtisch",
    who: "Mitglieder",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcpbkc/",
    description: "<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ",
    visibility: "public",
    member_pay_fee: false
    },
    {
    created: 1602930895000,
    duration: 7200000,
    id: "273995337",
    name: "Gerard Donovan, by Julius Winsome",
    date_in_series_pattern: false,
    status: "upcoming",
    time: 1605031200000,
    local_date: "2020-11-10",
    local_time: "19:00",
   updated: 1602930924000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 8,
    venue: {
    id: 27005496,
    name: "M-A-T Korean",
    lat: 48.13764190673828,
    lon: 11.545456886291504,
    repinned: false,
    address_1: "Schießstättstraße 2",
    city: "München",
    country: "de",
    localized_country_name: "Germany"
    },
    is_online_event: false,
    group: {
    created: 1503946106000,
    name: "One Dark and Stormy Night : Book Club",
    id: 25682270,
    join_mode: "approval",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Dark-And-Stormy-Night",
    who: "Members",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin"
    },
    link: "https://www.meetup.com/Dark-And-Stormy-Night/events/273995337/",
    description: "<p>Julius Winsome lives in a cabin in the hunting heartland of the Maine woods, with only his books and his dog for company. That is until the morning he finds that his dog has been shot dead - and not by accident. Gerard Donovan weaves an extraordinary tale of revenge that is also a tender and heartbreaking paean to lost love.<br/>\\</p> ",
    visibility: "public",
    member_pay_fee: false
    }
    ]
    }
    
    export {mockEvents};